# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            mdw.la
description:      'Matt Welsh'
url:              http://mdwelsh.github.io
baseurl:          http://www.mdw.la/

author:
  name:           'Matt Welsh'
  url:            http://www.mdw.la

paginate:         5
