# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            mdw.la
description:      'Matt Welsh'
url:              https://mdwelsh.github.io
#baseurl:          /

author:
  name:           'Matt Welsh'
  url:            https://www.mdw.la

paginate:         5
